# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EussDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod "SDWebImage"
pod "SVProgressHUD"
pod "MJExtension"
pod "MJRefresh"
pod "SDWebImage/GIF"

pod "DACircularProgress"
pod "pop"
pod "NJKWebViewProgress"



end
